
'use server';
/**
 * @fileOverview This file defines the function for validating a synthesized lesson using Gemini API.
 *
 * @exports validateLesson - The main function to validate a lesson draft.
 */

import { z } from 'zod';
import { generateWithGemini } from '@/lib/gemini';
import { parseGeminiJson } from '@/lib/utils';
import { SynthesizeLessonOutputSchema, ValidateLessonOutputSchema } from './types';


const ValidateLessonInputSchema = z.object({
  lessonDraft: SynthesizeLessonOutputSchema.describe('The lesson object to be validated.'),
});
type ValidateLessonInput = z.infer<typeof ValidateLessonInputSchema>;
type ValidateLessonOutput = z.infer<typeof ValidateLessonOutputSchema>;

export async function validateLesson(input: ValidateLessonInput): Promise<ValidateLessonOutput> {
  // We only need to send the content for validation, not the whole object
  const lessonContentForValidation = {
    title: input.lessonDraft.title,
    overview: input.lessonDraft.overview,
    content: input.lessonDraft.content,
  };
  const lessonDraftString = JSON.stringify(lessonContentForValidation, null, 2);
  
  const prompt = `You are an expert quality assurance editor for educational content. Your task is to review and validate a lesson draft generated by another AI.

Analyze the provided lesson draft:
'''json
${lessonDraftString}
'''

**Validation Criteria:**

1.  **Factual Accuracy:** Is the information correct and up-to-date? Are there any misleading statements or technical errors?
2.  **Clarity and Coherence:** Is the lesson well-structured and easy to understand for the target audience? Does it flow logically? Is the content at least 600 words?
3.  **Originality:** Does the content appear to be synthesized and original, or is it just copied from a few sources? (You don't have the original sources, but you can judge based on the writing style).
4.  **Completeness:** Does the lesson fulfill the goals outlined in its summary and introduction?

**Your Task:**

1.  Provide a 'confidence_score' from 0.0 (very low quality) to 1.0 (perfectly written).
2.  Set 'valid' to \`true\` only if the 'confidence_score' is 0.7 or higher. Otherwise, set it to \`false\`.
3.  If 'valid' is \`false\`, you MUST populate the 'issues' array with specific, actionable problems that need to be fixed. For each issue, provide a 'type' and a 'detail'.

Your final output must be a single, valid JSON object that strictly conforms to the output schema.
`;

  const aiText = await generateWithGemini(prompt);
  console.log('[validateLesson] AI raw preview:', aiText.slice(0, 500));
  let output = parseGeminiJson<ValidateLessonOutput>(aiText);

  // Enforce the business rule: if score < 0.7, valid must be false.
  if (output.confidence_score < 0.7 && output.valid) {
    output.valid = false;
    if (output.issues.length === 0) {
      output.issues.push({
        type: 'Low Confidence',
        detail: `The overall confidence score of ${output.confidence_score} is below the required threshold of 0.7, but no specific issues were itemized. Manual review is required.`,
      });
    }
  }
  
  return ValidateLessonOutputSchema.parse(output);
}
