
'use server';
/**
 * @fileOverview This file defines the Genkit flow for validating a synthesized lesson.
 *
 * The flow takes a lesson draft as input and uses an AI model to check for factual accuracy,
 * plagiarism, and logical errors. It returns a validation result object.
 *
 * @exports validateLesson - The main function to validate a lesson draft.
 */

import { ai } from '../../../../genkit.config';
import {z} from 'zod';
import { googleAI } from '@genkit-ai/google-genai';

const OutputSourceSchema = z.object({
    title: z.string().describe("The title of the source."),
    url: z.string().url().describe("The URL of the source."),
    domain: z.string().describe("The domain of the source."),
    type: z.enum(['article', 'doc', 'tutorial', 'video']).describe("The type of content."),
    short_note: z.string().describe("A brief note on why this source is relevant or useful (1-2 sentences)."),
});

const VideoSchema = z.object({
    title: z.string().describe("The title of the video."),
    url: z.string().url().describe("The original YouTube watch URL (not an embed link)."),
    channel: z.string().describe("The name of the YouTube channel, if available."),
});

const SynthesizeLessonOutputSchema = z.object({
  title: z.string().describe('A clear and concise title for the lesson.'),
  overview: z.string().describe('A short introductory paragraph that summarizes the main content of the lesson.'),
  content: z.string().describe('The full lesson content in Markdown or HTML format, between 800 and 1200 words, with clear sections and practical examples.'),
  sources: z.array(OutputSourceSchema).describe('A curated list of the most reliable sources used for synthesis.'),
  videos: z.array(VideoSchema).describe('A list of relevant videos found in the sources.'),
});

const ValidateLessonInputSchema = z.object({
  lessonDraft: SynthesizeLessonOutputSchema.describe('The lesson object to be validated.'),
});
type ValidateLessonInput = z.infer<typeof ValidateLessonInputSchema>;

const ValidateLessonOutputSchema = z.object({
  valid: z.boolean().describe('A boolean indicating if the lesson is considered valid and ready for use.'),
  confidence_score: z.number().min(0).max(1).describe('A score from 0.0 to 1.0 representing the confidence in the lesson\'s quality.'),
  issues: z.array(
    z.object({
      type: z.string().describe('The type of issue found (e.g., "Factual Error", "Plagiarism Concern", "Clarity").'),
      detail: z.string().describe('A detailed description of the specific issue.'),
    })
  ).describe('A list of issues found in the lesson draft. Empty if the lesson is valid.'),
});
type ValidateLessonOutput = z.infer<typeof ValidateLessonOutputSchema>;

export async function validateLesson(input: ValidateLessonInput): Promise<ValidateLessonOutput> {
  return validateLessonFlow(input);
}

const validatePrompt = ai.definePrompt({
  name: 'validateLessonPrompt',
  input: {schema: z.object({ lessonDraftString: z.string() })},
  output: {schema: ValidateLessonOutputSchema},
  prompt: `You are an expert quality assurance editor for educational content. Your task is to review and validate a lesson draft generated by another AI.

Analyze the provided lesson draft:
'''json
{{{lessonDraftString}}}
'''

**Validation Criteria:**

1.  **Factual Accuracy:** Is the information correct and up-to-date? Are there any misleading statements or technical errors?
2.  **Clarity and Coherence:** Is the lesson well-structured and easy to understand for the target audience? Does it flow logically? Is the content at least 600 words?
3.  **Originality:** Does the content appear to be synthesized and original, or is it just copied from a few sources? (You don't have the original sources, but you can judge based on the writing style).
4.  **Completeness:** Does the lesson fulfill the goals outlined in its summary and introduction?

**Your Task:**

1.  Provide a 'confidence_score' from 0.0 (very low quality) to 1.0 (perfectly written).
2.  Set 'valid' to \`true\` only if the 'confidence_score' is 0.7 or higher. Otherwise, set it to \`false\`.
3.  If 'valid' is \`false\`, you MUST populate the 'issues' array with specific, actionable problems that need to be fixed. For each issue, provide a 'type' and a 'detail'.

Your final output must be a single, valid JSON object that strictly conforms to the output schema.
`,
});

const validateLessonFlow = ai.defineFlow(
  {
    name: 'validateLessonFlow',
    inputSchema: ValidateLessonInputSchema,
    outputSchema: ValidateLessonOutputSchema,
  },
  async input => {
    const {output} = await validatePrompt({
        lessonDraftString: JSON.stringify(input.lessonDraft),
      }, { model: googleAI.model('gemini-1.5-pro-001') });

    if (!output) {
      throw new Error('Failed to get a valid response from the AI model.');
    }

    // Enforce the business rule: if score < 0.7, valid must be false.
    if (output.confidence_score < 0.7 && output.valid) {
      output.valid = false;
      if (output.issues.length === 0) {
        output.issues.push({
          type: 'Low Confidence',
          detail: `The overall confidence score of ${output.confidence_score} is below the required threshold of 0.7, but no specific issues were itemized. Manual review is required.`,
        });
      }
    }
    
    return output;
  }
);
